apiVersion: apps/v1
kind: Deployment
metadata:
  name: omniguard-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omniguard-backend
  template:
    metadata:
      labels:
        app: omniguard-backend
      annotations:
        alpha.image.policy.openshift.io/resolve-names: "*"
    spec:
      containers:
        - name: backend
          image: omniguard-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: omniguard-backend-config
            - secretRef:
                name: omniguard-backend-secret
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
