apiVersion: apps/v1
kind: Deployment
metadata:
  name: omniguard-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omniguard-frontend
  template:
    metadata:
      labels:
        app: omniguard-frontend
      annotations:
        alpha.image.policy.openshift.io/resolve-names: "*"
    spec:
      containers:
        - name: frontend
          image: omniguard-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
